# Generated by Django 3.0.4 on 2020-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='orderrnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
